// Generated by CoffeeScript 1.10.0
module.exports = function(message, code) {
  var err;
  this.message = message;
  this.code = code != null ? code : "unknown";
  if (this.message instanceof Error) {
    err = this.message;
    this.messave = err.message;
    return this.stack = err.stack;
  } else {
    Error.captureStackTrace(this, this.constructor);
    return this.code = "ERR_" + (this.code.toUpperCase());
  }
};

(require("util")).inherits(module.exports, Error);
